repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: ["--strict"]
        additional_dependencies:
          - "typer>=0.21.0,<0.22"
          - "rich>=14.2.0,<15"
          - "fastapi>=0.128.0,<0.129"
          - "pydantic>=2"
          - "pytest>=8.3.2"
          - "types-setuptools>=75.1.0.20241126"
        files: ^open_arbitrage/
